# Generated by Django 6.1 on 2026-09-24 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_branch_map_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Optional — makes the directions button open a precise pin instead of a text search. In Google Maps: long-press the exact spot on the map, then copy the first number shown at the bottom of the screen.",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
    ]
