# Generated by Django 6.0.7 on 2026-08-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        help_text="Short caption shown under the poster, e.g. the promo headline.",
                        max_length=200,
                    ),
                ),
                ("image", models.ImageField(upload_to="posters/")),
                (
                    "posted_date",
                    models.DateField(
                        help_text="Date this poster/promo is for — controls display order."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide without deleting (e.g. an expired promo).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-posted_date", "-created_at"],
            },
        ),
    ]
